version: '3.8'
services:
  app:
    build: .
    container_name: app
    ports:
     - 3000:3000
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev
    depends_on:
      - database
    restart: always

  database:
    image: postgres:15-alpine
    container_name: my-node-dock-app-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer:4.8.1
    depends_on:
      - database
    ports:
      - 8081:8080
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DEFAULT_USER=postgres
      - ADMINER_DEFAULT_PASSWORD=postgres
      - ADMINER_DEFAULT_DB=postgres
    
volumes:
  postgres_data: